### ISSUE TITLE
Añadir sección de proyectos

### ISSUE THREAD

**Issue by daavoo** [VigoTech/vigotech.github.io#18]
Como comentaba por correo, estaría guay una sección que sirva como referencia de proyectos de software libre hechos por gente de las comunidades (o en los que se colabora). 

Estaría bien algo así como un listado (filtrable por lenguaje de programación?) con el nombre, descripción y links al repositorio y/o correo de contacto.

Quizás esto pueda resultar útil:

https://github.com/lepture/github-cards

Añado que estaría bien implementarlo de manera que se pueda añadir un nuevo proyecto de manera sencilla (quizás una plantilla para rellenar por pull-request y que al hacer merge ya actualice la página??).

Ahí queda :)

Si nadie se anima a hacerlo, me animo yo. Aunque dado que veo que hay curro con el "branding" quizás mejor que lo haga alguien que lo integre bien en el diseño.

**Comment by antonmry** [comment]
@daavoo moi boa pinta! Non coñecía github-cards é tes razón que pode quedar moi ben.  Se fas unha PR cas modificacións no tema e un primeiro Markdown con algúns proxectos (eu meto un), eu encárgome da parte da automatización (xa a teño medio feita polos videos). ¿Qué che parece?

**Comment by daavoo** [comment]
Paréceme :+1: 

Pull request incoming.

**Comment by antonmry** [comment]
Xenial! Se tes calquera dúbida con Hugo, faime un ping no Slack: https://vigotechalliance.slack.com/messages

**Comment by daavoo** [comment]
@antonmry  #21

**Comment by antonmry** [comment]
Feito o merge. En canto teña un oco, vou a facer para que aparezan na portada de forma aleatoria. Gracias!
