### ISSUE TITLE
Eliminar as "post-date" nas "page"

### ISSUE THREAD

**Issue by daavoo** [VigoTech/vigotech.github.io#23]
Penso que non pinta nada a fecha de publicación arriba de todo nas páxinas individuais de proxectos e charlas.

Link de interese:

https://discuss.gohugo.io/t/content-is-it-same-for-page-and-post-and-how-to-hide-date/2246/3

**Comment by antonmry** [comment]
En xeral temos que mellorar o deseño das páxinas, está moi moi feo xa que o tema non ten soporte para esa parte

**Comment by daavoo** [comment]
@antonmry Hai plan de cambiar o tema a curto prazo?? Digo por que se non boto eu unha ollada a ver como elimiar as fechas das pages co tema actual

**Comment by antonmry** [comment]
Sí, está @sergiocarracedo traballando nesa parte. Creo que o está adaptando pero IMHO mellor agardar un pouco para non pisarse

**Comment by daavoo** [comment]
:+1:
