### ISSUE TITLE
Definir política para estar en VigoTech

### ISSUE THREAD

**Issue by antonmry** [VigoTech/vigotech.github.io#37]
Crear unha PR inicial e aprobar por todos os grupos

**Comment by ediazcomellas** [comment]
También una persona de contacto o una forma de anotarse.

**Comment by ediazcomellas** [comment]
# Ideas de criterios para aceptar a un nuevo grupo

Se trata de establecer criterios que permitan discriminar objetivamente si un grupo entra bajo el paraguas de vigotech o no. Esta lista de criterios son, en realidad, otra forma de definir lo que es vigotech, por lo que es importante que estemos todos de acuerdo.

Yo veo Vigotech como un impulsor de iniciativas de carácter tecnológico, mediante incremento de visibilidad, compartir experiencias organizativas, cooperación entre participantes, etc. Por ello, para que un grupo interesado en pertenecer a Vigotech se convierta en parte, creo que debe cumplir:

- Ser un grupo de tamaño relevante (si son sólo una o dos personas, probablemente encajen mejor como parte de otro grupo)
- Tener vocación abierta (si es un club que restringe el acceso, por ejemplo, sería difícil que otros miembros del Vigotech pudiesen sacar partido de este nuevo grupo)
- Organizar eventos/reuniones/etc. Para evitar listar y eliminar miles de grupos, propongo que sólo se incluya oficialmente al grupo tras dos o tres reuniones. 

Esto es sólo una idea... a completar y mejorar!

**Comment by antonmry** [comment]
Eu coincido con @ediazcomellas e añado:

- Creo que sería bo establecer un criterio para grupos inactivos: se non fixo un meetup en 6 meses, se quita temporalmente.
- Eliminaría o requisito os grupos novos: xa bastante é montalo e VigoTech pode axudar a difundir a sua existencia nos primeiros pasos. Así terían o menos 6 meses para o lanzamento.
- Creo que os grupos deberían ter unha canle no Slack, ainda que non a usen, é unha boa forma de estar todos xuntos nalgún sitio, e outra xente, sin ser os organizadores, poden colaborar.

Hai algunha cousa que faria falta especificar para evitar problemas: qué pasa cando alguén dun grupo se escinde para montar unha temática parecida. No noso caso, encantados, pero igual que non o toma tan ben (houbo problemas varios en BCN con iso).

Tamén deixaría clara a temática. A mín persoalmente no me gustaría ver metidos grupos de temática no tecnoloxica tipo ganchillo ou startups, hai outros foros para iso

**Comment by ediazcomellas** [comment]
Ben visto @antonmry.

O requisito para os grupos novos é para incluilos "oficialmente" no panel e en seguintes edicións da cartelería. Dende logo, sería bo que nas reunións de todos os grupos se avisase da existencia de novas iniciativas.

Hai un requisito (obvio) máis que esquecín antes: ter unha persoa de contacto polo menos.

**Comment by sergiocarracedo** [comment]
Requisito a pedir a cualquier grupo que pretenda integrarse en Vigotech, es que organice regularmente eventos en Vigo, podríamos fijar un mínimo de 6 al año.

**Comment by migonzalvar** [comment]
@antonmry comentou:

> Creo que os grupos deberían ter unha canle no Slack, ainda que non a usen, é unha boa forma de estar todos xuntos nalgún sitio, e outra xente, sin ser os organizadores, poden colaborar.

Na miña opinión a canle de Slack é un servicio pero en ningún caso debería ser obligatorio telo. Pode ser contraproducente pois se non hai resposta pode dar a impresión de abandono. É escravo, require que a xente esté conectada sempre e non todo o mundo pode ter un canal de chat 

Consideración a parte e o tema da plataforma Slack, qué e un *servicio gratuito* pero [un xardín cercado](https://en.wikipedia.org/wiki/Closed_platform).

Por iso, no meu caso non o considero un canal oficial do meu grupo.

Resumindo: non estou en contra de que se empregue, pero creo que non se debe obrigar a que exista.

**Comment by migonzalvar** [comment]
@sergiocarracedo comentou en https://github.com/VigoTech/vigotech.github.io/issues/37#issuecomment-309439710

> Requisito a pedir a cualquier grupo que pretenda integrarse en Vigotech, es que organice regularmente eventos en Vigo, podríamos fijar un mínimo de 6 al año.

Creo que 6 é demasiado. Eu diría simplemente regular. Podería ser un evento o ano pero moi grande e para min encaixaríá dentro da definición (estou pensando nunha cousa tipo feria ou congreso).

**Comment by antonmry** [comment]
@migonzalvar hai grupos que teñen unha canle do slack, cando alguén pregunta, sempre hai alguén que avisa de que é mellor preguntar na lista de correo ou no Telegram, onde hai máis actividade para ese grupo.

En calquera caso, sexa Slack ou outra cousa, creo que sería bo que os grupos tiveran unha plataforma de comunicación conxunta, onde a xente sepa que está todo o mundo de VigoTech.

**Comment by antonmry** [comment]
Unha opción intermedia a valorar e facer dos categorías de grupos:

Grupos VigoTech: tecnolóxico sen ánimo de lucro, con sede en Vigo, eventos en Vigo (con un mínimo a acordar), animan o Celta, teñen mínimo un familiar traballando en PSA e outro en Ourense :-)
Grupos amigos VigoTech: no cumpren algúns dos criterios anteriores pero son "aprobados" por todos os grupos VigoTech.
Os dous grupos receben o mesmo (lista de correo, Slack, presencia na web pero en seccións diferentes, twittter, etc.). 

(ver correo Grupo perdido)

**Comment by tomasalmeida** [comment]
Yo añadiría otro criterio más que aunque parezca absurdo, me parece necesario ponerlo, que el grupo haga eventos. Es decir, aunque sea un grupo amigo que no haga eventos, me parece absurdo que promovamos este grupo.

**Comment by sergiocarracedo** [comment]
@tomasalmeida estoy de acuerdo, pero para no dejar fuera a nadie podriamos establecer una figura de miembro temporal: Ejemplo, un grupo de madrid/Orense/Lugo.... quiere hacer una charla aqui (habitualmente lo harían junto con un grupo de vigotech, supongamos que no) ese grupo podria entrar temporalmente como "miembro honorifico" y asi aparece en el calendario y demás. Además si es posible les pediria que mencionasen vigotech en su "evento"

**Comment by tomasalmeida** [comment]
Hola @sergiocarracedo, me he explicado mal. Con que haga un evento, es que haga algún evento en Vigo, Ourense, Coruña o cualquier otro lugar! Como ejemplo, el PortoJUG que sólo tuvo un evento en 2015. Este grupo no me parece un grupo eligible para promoción. Deberíamos promover grupos que están activos actualmente (si es en Vigo mejor, pero eso es otra discusión).

**Comment by alexhermida** [comment]
Boas, tal y cómo comentamos na última reunión. Seguimos a conversa por PR con o documento en curso. Se o vedes necesario podemos abrir outra issue. Intentei simplificar os temas que aquí se falaron..no dubidedes en comentar ou facer PR por favor.

https://github.com/VigoTech/documentos/blob/master/condicionsentrada.md
