### ISSUE TITLE
Carta de presentación / manifiesto VigoTech

### ISSUE THREAD

**Issue by antonmry** [VigoTech/vigotech.github.io#41]
Entre a páxina de benvida e a do listado dos grupos, estaría ben meter unha presentación do VigoTech cos seus valores e obxetivos. Algo de texto, en plan parrafada, e pode que con algún enlace interno (por exemplo os requisitos de entrada de #37)

Se alguén se anima a redactala pero non quere pelexar con Hugo, que a poña en plan comentario/PR e xa me encargo de adaptala.

**Comment by alexhermida** [comment]
Un primeiro esbozo. Cómo falamos, intentemos continuar por PR.

https://github.com/VigoTech/documentos/blob/master/manifiesto.md
