### ISSUE TITLE
Erro nos proxectos

### ISSUE THREAD

**Issue by antonmry** [VigoTech/vigotech.github.io#47]
Hai un erro na libreria das cards e está facendo cousas raras (ver imaxen o final) (reportado por @sergiocarracedo )

O erro é https://github.com/lepture/github-cards/issues/45 (gracias @danybmx)

Desactivei os proxectos ata que se resolva: https://github.com/VigoTech/vigotech.github.io/pull/46

![2017-05-30-121312_740x739_scrot](https://cloud.githubusercontent.com/assets/7526373/26579615/cda05b92-4534-11e7-9239-555fca2a5316.png)

Copio a @daavoo que traballou nesta parte.

**Comment by daavoo** [comment]
OUCH!

La verdad que me había pasado en mi móbil pero pensaba que había sido un problema puntual.

Le echo un ojo al plugin a ver que puede pasar y si no creo que igual es una opción más sencilla guardar el html de las cartas en el propio repo. Además ya me estaba a mí picando la mosca de que es un poco innecesario el andar haciendo peticiones a la API de Github todo el rato pudiendo guardar los proyectos en estático.

En rato libre le echo un ojo. Si alguien anda con esto. Ping me para no solaparnos.

**Comment by antonmry** [comment]
Creo que tamén está Sergio. Non é nada urxente, polo de agora o quitei da landing page ata que a cousa estea máis estable

**Comment by sergiocarracedo** [comment]
Solucionado en 7fc14ae456874b6c1c46ad4f1d254810b3e6845f , o widget tiña un pequeño problema de carga de un script por http en entornos https.
Engadin un parametro ficticio a url en <script src="//cdn.jsdelivr.net/github-cards/latest/widget.js?bugfix"></script> para saltar a cache do anterior
