### ISSUE TITLE
Añadir automáticamente los vídeos de Sysadmin@Galicia desde su feed de podcast

### ISSUE THREAD

**Issue by rubenrua** [VigoTech/vigotech.github.io#49]
La URL del feed es:

https://replay.teltek.es/podcast/series/58af67c7a7bc283f008b456c/collection.xml

**Comment by antonmry** [comment]
Recibido, poñome con isto cando teña un rato aproveitando que estou a refactorizar esa parte.

**Comment by rubenrua** [comment]
Si necesitas ayuda no dudes en avisar. 

Cuando tenga la URL del feed de las pyday te la mando.

**Comment by antonmry** [comment]
No debería haber problema, es más que nada que tengo que sacar algunas cosas del VigoJUG antes y ya me pongo con esto.

Aquí el branch: https://github.com/VigoTech/vigotech.github.io/tree/gorefactor

**Comment by antonmry** [comment]
@rubenrua nos podrías pasar los feeds del resto de videos (WomenTechMakers, PyDay, etc.). @sergiocarracedo está trabajando en ello y molaba tenerlos todos

**Comment by rubenrua** [comment]
Índice de los podcast de `Teltek Replay`: https://replay.teltek.es/podcast/list.xml

* Sysadmin galicia: https://replay.teltek.es/podcast/series/58af67c7a7bc283f008b456c/collection.xml
* PyDay Galicia 2017: https://replay.teltek.es/podcast/series/593ea555a7bc288d038b45c8/collection.xml
* JoomlaDay 2017: https://replay.teltek.es/podcast/series/593ea555a7bc288d038b45c8/collection.xml
* Womentechmakers 2018: https://replay.teltek.es/podcast/series/5ab61a9a2b81aa3a008b4570/collection.xml


En el feed podcast, el archivo de video `mp4` es el side-by-side. Para usar el player multi-stream (el bueno) usar la URL https://replay.teltek.es/videoplayer/%id%?autostart=false, donde `%id` el el identificador del `item`.

Por ejemplo: https://replay.teltek.es/videoplayer/58af67a9a7bc2842008b4569?autostart=false

@sergiocarracedo Si necesitas ayuda no dudes en avisarnos (cc @pnieto)

**Comment by sergiocarracedo** [comment]
De momento he hecho la integración con video.js, veo de usar vuestro player en la siguiente iteración

**Comment by rubenrua** [comment]
Avisanos si te podemos ayudar con la siguiente iteración. .

**Comment by sergiocarracedo** [comment]
@rubenrua duda: Como saco el id correcto del del video para el player?
Por ejemplo, de https://replay.teltek.es/podcast/series/58af67c7a7bc283f008b456c/collection.xml, tengo el primer video "Contenerización de servicios en producción con Docker" el guid es https://dls-replay.teltek.es/pumukit/58af67c7a7bc283f008b456c/593eb02ba7bc28f10b8b4580.mp4, estraigo del la url cualquiera de los dos "hashes" y los coloco en la url del player

https://replay.teltek.es/videoplayer/593eb02ba7bc28f10b8b4580?autostart=false
https://replay.teltek.es/videoplayer/58af67c7a7bc283f008b456c?autostart=false

y en ambos casos obtengo un 404
