### ISSUE TITLE
Obxetivos 2017

### ISSUE THREAD

**Issue by antonmry** [VigoTech/vigotech.github.io#57]
Por @alexhermida

Objetivos para este año. Cada grupo tiene sus objetivos individuales, qué queremos de VigoTech a medio plazo? que aporta a los grupos y/o la comunidad? (30’)

**Comment by tomasalmeida** [comment]
Mis propuestas
- Mejorar la calidad técnica de los informáticos vigueses.
- Poner Vigo como un sitio rentable para empresas de calidad.
- Traer ponentes de nivel mundial (gente de GNU, OSI, Google, Facebook, etc etc..)

**Comment by ediazcomellas** [comment]
Yo añado:

- Pasarlo bien
