### ISSUE TITLE
Definir código de conducta

### ISSUE THREAD

**Issue by antonmry** [VigoTech/vigotech.github.io#60]
Ver https://github.com/gpul-labs/labs2017/blob/master/docs/codigodeconducta.md

**Comment by capri99** [comment]
Yo simplemente retocaría el tema de "patrocinadores" -> "patrocinios", "colaboradores" -> "colaboraciones", "voluntarios" -> "voluntariado", etc. Intentaría utilizar más el término "personas".
👍 Algo así hicimos en http://galicia2017.librecon.io/codigo-de-conducta/ Por favor, copia y pega lo que sea útil.

**Comment by alexhermida** [comment]
Unha primeira versión coa base que comenta @antonmry mais os axustes de @capri99 

https://github.com/VigoTech/documentos/blob/master/codigodeconducta.md

O dito seguimos por PR 😄

**Comment by antonmry** [comment]
@alexhermida eu como digades pero algunhas ideas:

- Molaba ter todos estes documentos neste repositorio, para que tamén apareceran na web (poden ser `pages` e que non aparezan linkadas no index.
- O seu sería facer unha PR, non?. O que linkas xa son os documentos en master.

**Comment by antonmry** [comment]
Creei unha PR: https://github.com/VigoTech/vigotech.github.io/pull/76 . Podemos seguir alí
