### ISSUE TITLE
Condiciones para difusión y retweets

### ISSUE THREAD

**Issue by ediazcomellas** [VigoTech/vigotech.github.io#65]
El objetivo de este issue es ponernos de acuerdo con qué cosas se difundirán desde VigoTech, bien oficialmente en la agenda o mediante redes sociales (twitter, etc). 

En primer lugar: todas las actividades de los grupos pertenecientes a VigoTech merecen (en mi opinión) redifusión oficial y en redes sociales. 

Sobre la atención a grupos externos, organizaciones y empresas, hay varios argumentos a considerar:

1. Queremos favorecer las iniciativas locales, la creación de trabajo en el entorno y el ecosistema tecnológico. Eso podría implicar que cualquier organización o empresa que hiciese alguna actividad o tuviese una oferta de trabajo merecería un comentario desde VigoTech
2. Debemos tener cuidado en hacer redifusión sólo a cosas de calidad, por lo que deberíamos establecer unos criterios mínimos.
3. Tampoco estamos aquí para hacer gratis el trabajo de otros. Si las empresas necesitan publicidad, que la paguen, ¿no?

Es posible que algunos tweets no sean apropiados para VigoTech, pero sí para algún grupo particular.

Por eso, sería bueno consensuar criterios para la redifusión. ¿Opiniones?

**Comment by tomasalmeida** [comment]
Voy a basarme en nuestras issues abiertas (están abiertas y por lo tanto son posiblemente modificables) que hablan sobre un poco que es o que es estar en VigoTech:

* Definir política para estar en VigoTech #37
* Carta de presentación / manifiesto VigoTech #41
* Obxetivos 2017 #57
* Definir código de conducta #60

Según veo, hacer promoción de tweet's de empresas no va en contra de ninguno de nuestros "ideales", por lo tanto se podría hacer promoción tranquilamente. 

Por otro lado, seguramente las empresas que hacen eventos quieren además de promover la charla, mejorar su cara frente a la comunidad informática en Vigo y posicionarse como un sítio atractivo para nosotros. No me parece mal tampoco, otras empresas ya cedieron sus espacios para eventos y no hubo problemas.

Yo añadiría como criterio que el evento no hiere el código de conducta y que sea grátis.

**Comment by alexhermida** [comment]
Yo estoy de acuerdo con el sentimiento general y creo efectivamente que las empresas se puedan apoyar en VigoTech para la búsqueda de talento o difundir eventos de interés general para la comunidad tecnológica, de hecho son algunos de los objetivos en si mismos de la iniciativa. 

Ahora bien, también estamos trabajando y llegaremos a consenso en lo que a manifiesto y código de conducta se refiere. No tendría sentido promocionar empresas/organizaciones/eventos que no sean afines.

Estoy en gran medida en lo que comentas @tomasalmeida aunque no me parece requisito que siempre los eventos difundidos sean gratuitos. De hecho, en muchos casos, eventos de los propios grupos de la comunidad, como talleres o eventos de embergadura no lo serán, pero por ello no deberíamos dejar fuera de la difusión de interés general. Otro caso sería, que sean con ánimo de lucro.
