### ISSUE TITLE
HashCode 2018

### ISSUE THREAD

**Issue by antonmry** [VigoTech/vigotech.github.io#69]
O HashCode é unha competición de programación de Google que se fai o 1 de Marzo de 18:30 a 22:30. É por grupos de 2 a 4 persoas. Os que mellor queden na clasificación serán invitados por Google a unha competición en Dublin o 28 de Abril.

A idea é que o VigoTech proporcionará un Hub (o podes marcar cando te rexistras) que permitirá:

* Dar visibilidade dos equipos na zona de Vigo.
* Xuntarse nun local para facelo xuntos (A Industriosa / Kaleido Coworking).
* Se chegamos a 20 persoas no Hub antes do día 1 de Febreiro, Google enviará algúns detalles os asistentes.

O rexistro pódese facer dende a web: https://hashcode.withgoogle.com e unha vez rexistrado o equipo, pódese un unir o Hub de VigoTech.

A idea é:

- [ ] Confirmar a dispoñibilidade dos locais para esa data [A Industriosa / PythonVigo]
- [ ] Confirmar a dispoñibilidade de organizadores nesa data (tamén poden participar): eu case seguro non estarei fisicamente pola baixa de paternidade [ Voluntarios? ]
- [x] Publicar nos Twitter e Slack de VigoTech [Antón]
- [ ] Publicar a nivel de grupo (convocar en Meetup, listas de correos,etc.) [Grupos que queiran participar]
- [ ] Axudar os membros do teu grupo a facer equipos [Grupos que queiran participar]

**Comment by alexhermida** [comment]
Que facemos con esta @antonmry finalmente complicouse... a ver si para o ano. ¿Pechamos?

**Comment by antonmry** [comment]
si, toda a razón. Fechada!
