### ISSUE TITLE
vigotech.json

### ISSUE THREAD

**Issue by sergiocarracedo** [VigoTech/vigotech.github.io#71]
Propongo discutir la posibilidad de tomar como única fuente veraz de información sobre los grupos y el propio Vigotech un archivo json como el que pego más abajo para evitar la necesidad de mantener varias fuentes, por ejemplo, la web, el JPG / Slide de la lista de grupos, o cualquier fuente de información que podamos crear en el futuro.
La web por ejemplo generaría la página de grupos a partir de este json, al igual que una pequeña herramienta que estoy desarrollando para generar el slide de grupos.

[vigotech.json](https://github.com/sergiocarracedo/vigotech.github.io/blob/source/vigotech.json)

**Comment by antonmry** [comment]
A mín paréceme moi boa idea, a parte da web non debería ser complexa de facer

**Comment by Daniel-at-github** [comment]
Yo te aconsejo yaml, es más cómodo de editar/leer y se convierte fácilmente a json.

**Comment by alexhermida** [comment]
Eu o vexo 👍 como mellora propondría seguir un [json schema](http://json-schema.org/).

En calquer caso como paso inicial o vexo perfecto.

**Comment by sergiocarracedo** [comment]
@alexhermida ok, lo preparo sin problema.
Sobre los logos, creo que tambien a parte de proporcionar el link a la imagen, podriamos añadirlos al json como Base64, la idea (aunque aumente el peso del json) seria tener todo de una vez

**Comment by antonmry** [comment]
o de metelos en Base64 o vexo un pouco complexo, igual ter unha carpeta para meter os logos e a URL final no JSON é máis práctico
