### ISSUE TITLE
Hugo no genera contenido nuevo desde vigotech.json

### ISSUE THREAD

**Issue by josealfonsomora** [VigoTech/vigotech.github.io#81]
Ó executar `hugo server` 
```
Watching for changes in /Users/josealfonsomora/projects/vigotech.github.io/{content,static,themes}
Watching for config changes in /Users/josealfonsomora/projects/vigotech.github.io/config.toml
```
Pero nos o que necesitamos é que observe os cambio no archivo `vigotech.json`

Creei un PR, pero on contido non está modificado https://github.com/VigoTech/vigotech.github.io/pull/80

**Comment by antonmry** [comment]
Aínda non está implementado, podes seguir a conversa aquí: https://github.com/VigoTech/vigotech.github.io/issues/71

Polo de agora temos que añadir os cambios a man, é doado.. copiar outra PR y listo.

Fecho a issue por duplicada con https://github.com/VigoTech/vigotech.github.io/issues/71, ok?
