### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by antonmry** [VigoTech/vigotech.github.io#87]
Na nova versión, xa non vai... é unha magoa non poder a evolución da web

Código: UA-98368785-1

![image](https://user-images.githubusercontent.com/7526373/51466498-9ed4dd00-1d6a-11e9-99be-44c901d4e9cc.png)

**Comment by sergiocarracedo** [comment]
O preparo en canto poida, un detalle legal: En teoría isto implicaría amosar unha mensaxe de autorización das cookies de analitycs (ou de rechazo das mesmas), non?

**Comment by antonmry** [comment]
Seria o ideal, sí
